# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8c67502b6e18df8d6ed5aec6067ca86dca8fd668b274c412f93cee5ec177b963116f2542322f0502ce27330522af3642f21341bdd89c1cd3b28a72eee8a9e78

test:
  secret_key_base: 107ba2c4e52155e1fb44ca908aeaffdd77fac08357cdb1ea1db62dd3d18fb5f3a160b36951b1cd2357e116402c146dc0a273be19502451d97e7971f3b16c67d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
